"""Gate a file on the rules for code that leaves this fork.

Run it before porting anything to the shared repository. It is deliberately
mechanical: it does not judge whether the code is correct, only whether it still
carries things that must not be published, or shape that the receiving project
would have to clean up.

    python tools/check_upstream_ready.py eval/ interpretability/
    python tools/check_upstream_ready.py --max-docstring 15 eval/foo.py

Exit status is non-zero if any file has a finding, so it can gate a commit.
"""

import argparse
import ast
import os
import re
import sys

# Anything that identifies a person, an account, or a machine.
IDENTITY = [
    (re.compile(r"/n/home\d*/[A-Za-z0-9_.-]+"),      "absolute home path"),
    (re.compile(r"/n/holylfs\d*/[A-Za-z0-9_./-]+"),  "absolute lab-storage path"),
    (re.compile(r"\bholy[a-z0-9]+\.rc\.fas\.harvard\.edu\b"), "cluster hostname"),
    (re.compile(r"\bholy(?:login)?\d[a-z0-9]*\b"),   "cluster node name"),
    (re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"), "email address"),
    (re.compile(r"\b(?:arguelles_delgado|rc\.fas\.harvard)\b"), "institution reference"),
]

# Assistant / model references, which must never ship.
ASSISTANT = [
    (re.compile(r"\b(?:claude|anthropic|chatgpt|openai|copilot|gpt-?[0-9])\b", re.I),
     "assistant or model reference"),
    (re.compile(r"\b(?:AI[- ]generated|generated by an? AI|as an AI)\b", re.I),
     "assistant attribution"),
]

# Session archaeology: true when written, meaningless to a reader elsewhere.
EPHEMERAL = [
    (re.compile(r"\b20\d{2}-\d{2}-\d{2}\b"),                  "hard-coded date"),
    (re.compile(r"\bjob\s*#?\s*\d{6,}\b", re.I),              "scheduler job id"),
    (re.compile(r"\b(?:as of|fixed on|measured on|added)\s+20\d{2}\b", re.I),
     "dated aside"),
    (re.compile(r"\b(?:TODO|FIXME|XXX|HACK)\b"),              "unfinished marker"),
]

# Paths from this fork's layout, which does not exist in the shared repository.
LAYOUT = [
    (re.compile(r"\bdetector_optimization_v[0-9]\b"), "fork-only directory in a path"),
    (re.compile(r"\bmodules_v[345]\b"),               "legacy module path"),
]

GROUPS = [("identity", IDENTITY), ("assistant", ASSISTANT),
          ("ephemeral", EPHEMERAL), ("layout", LAYOUT)]


def scan_text(path, max_docstring):
    findings = []
    src = open(path, encoding="utf-8", errors="replace").read()

    for lineno, line in enumerate(src.splitlines(), 1):
        for group, rules in GROUPS:
            for rx, what in rules:
                m = rx.search(line)
                if m:
                    findings.append((lineno, group, what, m.group(0)[:60]))

    # Docstring bulk applies to Python only; the regex rules above already
    # covered shell and markdown.
    if not path.endswith(".py"):
        return findings

    # The narrative of how something was discovered belongs in notes, not in the
    # shipped file.
    try:
        tree = ast.parse(src)
    except SyntaxError as e:
        findings.append((e.lineno or 0, "syntax", "file does not parse", str(e)[:60]))
        return findings

    targets = [("module", tree)] + [
        (f"{type(n).__name__} {getattr(n, 'name', '?')}", n)
        for n in ast.walk(tree)
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    ]
    for label, node in targets:
        doc = ast.get_docstring(node)
        if doc and len(doc.splitlines()) > max_docstring:
            lineno = getattr(node, "lineno", 1)
            findings.append((lineno, "docstring",
                             f"{label} docstring is {len(doc.splitlines())} lines",
                             f"limit {max_docstring}"))
    return findings


def iter_files(paths):
    for p in paths:
        if os.path.isdir(p):
            for dirpath, dirnames, filenames in os.walk(p):
                dirnames[:] = [d for d in dirnames if d != "__pycache__"]
                for f in sorted(filenames):
                    if f.endswith((".py", ".md", ".sh", ".sbatch")):
                        yield os.path.join(dirpath, f)
        else:
            yield p


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("paths", nargs="+", help="files or directories to check")
    ap.add_argument("--max-docstring", type=int, default=20,
                    help="longest acceptable docstring, in lines (default 20)")
    ap.add_argument("--summary", action="store_true",
                    help="one line per file instead of every finding")
    args = ap.parse_args()

    total, dirty = 0, 0
    for path in iter_files(args.paths):
        findings = scan_text(path, args.max_docstring)
        if not findings:
            continue
        dirty += 1
        total += len(findings)
        if args.summary:
            kinds = {}
            for _, group, _, _ in findings:
                kinds[group] = kinds.get(group, 0) + 1
            spread = "  ".join(f"{k}={v}" for k, v in sorted(kinds.items()))
            print(f"{len(findings):4d}  {path:<52} {spread}")
        else:
            print(f"\n=== {path}")
            for lineno, group, what, snippet in findings:
                print(f"  {lineno:5d}  [{group}] {what}: {snippet}")

    print(f"\n{total} finding(s) across {dirty} file(s)")
    return 1 if total else 0


if __name__ == "__main__":
    sys.exit(main())

# Note on how to use this: it is a PRE-PORT gate, not a local linter. A finding
# like "legacy module path: modules_v4" is correct in this tree and wrong only
# once the file moves to a repository where v4 lives elsewhere. Run it on the
# ported copy, not on the working tree, and do not churn local files to silence it.
