"""FNN surrogate for detector optimization v6.

The FNN learns `(primary_features, layout) -> (E, T) per detector`. Ground-truth
labels are generated by applying v4's `GetCounts_planeaware` to cached
AllShowers point clouds — the cache is loaded once and never regenerated
during training or optimization.

Usage (from a driver script living in the v6 folder):

    import modules_v6   # triggers sys.path injection for v3 + v4
    from modules_v6.fnn_surrogate import (
        SHOWER_CACHE, GEOMETRY_PATH, EAST_ENTRY, LAYER_EAST_DX, N_PLANES,
        encode_primary, build_training_pairs, FNNSurrogate,
    )
"""

import os
from typing import Tuple

import numpy as np
import torch
import torch.nn as nn

# Require the v3+v4 sys.path injection (triggered by `import modules_v6`).
from modules_v4.tr_plane_kernel import GetCounts_planeaware

from .constants import (EAST_ENTRY, LAYER_EAST_DX, N_DETECTORS, SHOWER_CACHE, PRIMARY_DIM,
                        LOG_E_MIN, LOG_E_MAX)
from .detector_strategies import (_STRATEGIES, _STRATEGY_FNS)

# ── Primary encoding ─────────────────────────────────────────────────────────

def encode_primary(directions: torch.Tensor,
                   energies:   torch.Tensor,
                   pdg:        torch.Tensor) -> torch.Tensor:
    """Raw 5-feature primary encoding.

    Args:
        directions : (N, 3) unit vectors (sin θ cos φ, sin θ sin φ, cos θ).
        energies   : (N,) or (N, 1) primary energies [GeV], range ~[1e5, 1e8].
        pdg        : (N,) integer class ids (0 or 1 for this cache).

    Returns:
        (N, 5) tensor `[dir_x, dir_y, dir_z, log_e_norm, pdg]`
        where log_e_norm = (log10(E) - LOG_E_MIN) / (LOG_E_MAX - LOG_E_MIN) ∈ [0, 1].
    """
    dirs = torch.as_tensor(directions, dtype=torch.float32)
    eng  = torch.as_tensor(energies,   dtype=torch.float32).reshape(-1, 1)
    pdg  = torch.as_tensor(pdg,        dtype=torch.float32).reshape(-1, 1)
    log_e = torch.log10(eng)
    log_e_norm = (log_e - LOG_E_MIN) / (LOG_E_MAX - LOG_E_MIN)
    return torch.cat([dirs, log_e_norm, pdg], dim=1)



# ── Label computation (batched over showers, one shared layout per batch) ────

@torch.no_grad()
def compute_labels_batch(clouds:   torch.Tensor,
                         x_det:    torch.Tensor,
                         y_det:    torch.Tensor,
                         surface,
                         east_entry:    float = EAST_ENTRY,
                         layer_east_dx: float = LAYER_EAST_DX,
                         sigma_spatial: float = 200.0) -> Tuple[torch.Tensor, torch.Tensor]:
    """Run v4's plane-aware kernel on a batch of showers sharing one layout.

    Args:
        clouds : (B, max_points, 5) AllShowers point clouds.
        x_det  : (n_det,) North coordinates.
        y_det  : (n_det,) Up coordinates.
        surface: `SurfaceEastMap` — differentiable East = f(N, Up).

    Returns:
        E : (B, n_det) local intensities (v4 kernel `local_intensity`).
        T : (B, n_det) weighted-average times (v4 kernel `et`).
    """
    east   = surface(x_det, y_det)
    z_cont = (east_entry - east) / layer_east_dx

    dummy_flux = torch.tensor([0.0], device=clouds.device)
    E, T = GetCounts_planeaware(
        clouds, x_det, y_det, z_cont,
        SmearN_fn=None,
        fluxB_e=dummy_flux,
        TimeAverage_vectorized_fn=None,
        sigma=sigma_spatial,
    )
    return E, T


def build_training_pairs(mountain, surface,
                         shower_cache_path: str = SHOWER_CACHE,
                         batch_size:        int = 20,
                         max_showers:       int = 0,
                         seed:              int = 0,
                         device:            torch.device = torch.device("cpu"),
                         verbose:           bool = True,
                         recenter_to_mountain: bool = False,
                         load_chunk:        int = 4096):
    """Build (primary, xy, E, T) training tensors from the cached shower corpus.

    For every shower in the cache, one layout per strategy in `_STRATEGIES` is
    drawn (so `layouts_per_shower = len(_STRATEGIES)`). Within each strategy,
    showers are grouped into batches of `batch_size` that share one layout —
    this is what makes v4's non-batched kernel affordable in one pass.

    The kernel runs on `device` (GPU if available); outputs are returned on CPU.

    **Bounded-memory streaming.** The point clouds are NEVER loaded whole — a
    dense `(2N, 25088, 5)` corpus is ~301 GB at 300k pairs (OOM). Only the tiny
    metadata (dir/energy/pdg) is read up front; the clouds are streamed in
    chunks of `load_chunk` showers (loaded → used for all strategies → freed),
    so peak RAM is one chunk (~2 GB at 4096) regardless of corpus size. The two
    species blocks (electron rows [0, per_sp), muon rows [per_sp, 2·per_sp)) are
    each kept to a balanced prefix of `max_showers/2` rows so Step 2's pdg-split
    stays balanced — this matches `fnn_surrogate_ne.build_training_pairs` and
    differs from the old "first `max_showers` file rows" behaviour (identical
    when `max_showers` == full corpus). The per-(strategy, batch) random layouts
    are drawn in chunk-major order, so for a fixed seed the layout *assignment*
    differs from the old strategy-major loop (the distribution is unchanged).

    If `recenter_to_mountain` is True, each shower's particle-cloud xy is
    shifted so its energy-weighted centroid lands on the mountain bbox center
    (done per chunk, in place). The cache has most clouds at x in [-11k, 0],
    y in [-5k, 0] while the mountain bbox is roughly (-2.5k..+2.5k, +2.4k..+3.9k),
    so ~77% of raw showers don't trigger any detector. Recentering turns every
    shower into a useful training signal at the cost of decoupling impact point
    from primary direction.

    Returns:
        primaries : (N_pairs, 5)   float32
        xy        : (N_pairs, 100, 2) float32
        E         : (N_pairs, 100) float32
        T         : (N_pairs, 100) float32
        strategy_ids : (N_pairs,)  int64 — index into `_STRATEGIES`
    """
    import showerdata

    # Metadata only (tiny); the dense point clouds are streamed in chunks below.
    meta   = showerdata.load_inc_particles(shower_cache_path)
    n_file = meta.pdg.shape[0]
    per_sp = n_file // 2                                  # electron / muon block size
    keep   = n_file if not max_showers else min(int(max_showers), n_file)
    k_sp   = keep // 2                                    # rows kept per species
    n_showers = 2 * k_sp

    # Dataset row d → file row: electron block d∈[0,k_sp) → file d; muon block
    # d∈[k_sp,2k_sp) → file per_sp+(d-k_sp). Build metadata in dataset order.
    keep_idx = np.concatenate([np.arange(0, k_sp),
                               np.arange(per_sp, per_sp + k_sp)])
    dirs   = torch.as_tensor(meta.directions[keep_idx], dtype=torch.float32)  # (n_showers, 3)
    energs = torch.as_tensor(meta.energies[keep_idx],   dtype=torch.float32)  # (n_showers, 1)
    pdg    = torch.as_tensor(meta.pdg[keep_idx],        dtype=torch.long)     # (n_showers,)
    primaries_all = encode_primary(dirs, energs, pdg)                         # (n_showers, 5)

    if recenter_to_mountain:
        mtn_cx = 0.5 * (mountain.n_min + mountain.n_max)
        mtn_cy = 0.5 * (mountain.u_min + mountain.u_max)

    n_strat = len(_STRATEGIES)
    n_pairs = n_showers * n_strat
    n_det   = N_DETECTORS

    out_primary = torch.empty((n_pairs, PRIMARY_DIM), dtype=torch.float32)
    out_xy      = torch.empty((n_pairs, n_det, 2),     dtype=torch.float32)
    out_E       = torch.empty((n_pairs, n_det),        dtype=torch.float32)
    out_T       = torch.empty((n_pairs, n_det),        dtype=torch.float32)
    out_strat   = torch.empty((n_pairs,),              dtype=torch.int64)

    # Keep chunks a multiple of batch_size so no shared-layout batch is split
    # across a chunk boundary (only a block's final batch may be short).
    load_chunk = max(int(batch_size), (int(load_chunk) // int(batch_size)) * int(batch_size))
    if verbose:
        print(f"[load] streaming {n_showers} rows ({k_sp}/species) of {n_file} "
              f"in chunks of {load_chunk}; peak RAM ≈ one chunk, not the corpus")

    rng = np.random.default_rng(seed)
    n_sanitized = 0

    # Per species block: file rows are one contiguous slice (single disk read).
    for tag, file_start, ds_start in (("e", 0, 0), ("mu", per_sp, k_sp)):
        for c_lo in range(0, k_sp, load_chunk):
            c_hi = min(c_lo + load_chunk, k_sp)
            csz  = c_hi - c_lo

            # Stream this chunk's clouds; reused across all strategies, then freed.
            sub = showerdata.load(shower_cache_path,
                                  start=file_start + c_lo, stop=file_start + c_hi)
            clouds_chunk = torch.as_tensor(sub.points, dtype=torch.float32)   # (csz, P, 5)
            del sub

            # float32 energy de-transform overflows to +Inf in ~1% of muon
            # showers; in the kernel Inf·0 = NaN poisons E/T and NaN-trains the
            # surrogate. Treat any non-finite point as padding (zero its 5-vector
            # → energy<=0 drops it from the recenter mask and the kernel sums).
            bad = ~torch.isfinite(clouds_chunk).all(dim=-1)        # (csz, P)
            nb  = int(bad.sum())
            if nb:
                clouds_chunk[bad] = 0.0
                n_sanitized += nb

            if recenter_to_mountain:
                # Energy-weighted centroid over real points (padded rows stay 0).
                mask  = (clouds_chunk[:, :, 3] > 0).float()        # (csz, P)
                w_sum = mask.sum(dim=1).clamp(min=1.0)             # (csz,)
                cx = (clouds_chunk[:, :, 0] * mask).sum(dim=1) / w_sum
                cy = (clouds_chunk[:, :, 1] * mask).sum(dim=1) / w_sum
                dx = (mtn_cx - cx).view(-1, 1)
                dy = (mtn_cy - cy).view(-1, 1)
                clouds_chunk[..., 0] = clouds_chunk[..., 0] + dx * mask
                clouds_chunk[..., 1] = clouds_chunk[..., 1] + dy * mask

            for s_idx, (s_name, fn_name, kwargs) in enumerate(_STRATEGIES):
                fn = _STRATEGY_FNS[fn_name]
                for sb_lo in range(0, csz, batch_size):
                    sb_hi = min(sb_lo + batch_size, csz)
                    B = sb_hi - sb_lo

                    # Fresh shared layout for this batch
                    x_det, y_det = fn(mountain, n_det=n_det, rng=rng, **kwargs)
                    x_det = x_det.float().to(device)
                    y_det = y_det.float().to(device)

                    clouds = clouds_chunk[sb_lo:sb_hi].to(device)   # (B, P, 5)
                    E, T = compute_labels_batch(clouds, x_det, y_det, surface)

                    ds_lo = ds_start + c_lo + sb_lo
                    ds_hi = ds_start + c_lo + sb_hi
                    dst = slice(s_idx * n_showers + ds_lo, s_idx * n_showers + ds_hi)
                    out_primary[dst]  = primaries_all[ds_lo:ds_hi]
                    out_xy[dst, :, 0] = x_det.cpu().unsqueeze(0).expand(B, -1)
                    out_xy[dst, :, 1] = y_det.cpu().unsqueeze(0).expand(B, -1)
                    out_E[dst] = E.cpu()
                    out_T[dst] = T.cpu()
                    out_strat[dst] = s_idx

            del clouds_chunk
            if verbose:
                print(f"[build] {tag} rows {c_lo}-{c_hi}/{k_sp} done "
                      f"(×{n_strat} strategies)")

    if recenter_to_mountain and verbose:
        print(f"[recenter] shifted clouds to mountain center ({mtn_cx:.1f}, {mtn_cy:.1f})")
    if verbose and n_sanitized:
        print(f"[sanitize] zeroed {n_sanitized} non-finite points (float32 energy overflow)")

    return out_primary, out_xy, out_E, out_T, out_strat


def compute_normalization(primary:   torch.Tensor,
                          xy:        torch.Tensor,
                          E:         torch.Tensor,
                          T:         torch.Tensor) -> dict:
    """Per-feature z-score statistics for inputs and outputs.

    Input vector layout (for the FNN) is `[primary (5), xy_flat (200)]` = 205.
    Output vector layout is `[E (100), T (100)]` = 200 (first E then T).

    For the input, primary features (5) keep per-feature stats, but all xy
    slots share one (mean_x, std_x, mean_y, std_y) pair — otherwise
    permutation augmentation creates a train/val z-score mismatch.
    Likewise the output uses one shared (mean, std) for all E slots and
    one for all T slots.
    """
    n_det = E.shape[1]

    # ── Input: primary per-feature, xy shared across detectors ──────────
    p_mean = primary.mean(dim=0)                                    # (5,)
    p_std  = primary.std(dim=0).clamp(min=1e-10)                     # (5,)

    # One scalar mean/std for x coords, one for y coords
    xy_x = xy[..., 0]                                               # (B, n_det)
    xy_y = xy[..., 1]                                               # (B, n_det)
    x_mean = xy_x.mean();  x_std = xy_x.std()
    y_mean = xy_y.mean();  y_std = xy_y.std()

    # Broadcast to the full (205,) layout: [primary(5), x0,y0,x1,y1,...,x99,y99]
    xy_mean = torch.stack([x_mean.expand(n_det),
                           y_mean.expand(n_det)], dim=-1).reshape(-1)   # (200,)
    xy_std  = torch.stack([x_std.expand(n_det),
                           y_std.expand(n_det)], dim=-1).reshape(-1)    # (200,)

    in_mean = torch.cat([p_mean, xy_mean])                          # (205,)
    in_std  = torch.cat([p_std,  xy_std])                           # (205,)

    # ── Output: one shared stat for all E slots, one for all T slots ────
    E_mean = E.mean();  E_std = E.std()
    T_mean = T.mean();  T_std = T.std()

    out_mean = torch.cat([E_mean.expand(n_det),
                          T_mean.expand(n_det)])                    # (200,)
    out_std  = torch.cat([E_std.expand(n_det),
                          T_std.expand(n_det)])                     # (200,)

    return dict(
        in_mean=in_mean,   in_std=in_std,
        out_mean=out_mean, out_std=out_std,
    )


# ── FNN model ────────────────────────────────────────────────────────────────

class FNNSurrogate(nn.Module):
    """Flat MLP that maps (primary, layout) → (E, T) per detector.

    Input:  [primary (5) + xy_flat (2·100)] = 205 features.
    Output: [E (100), T (100)] = 200 features, reshaped to (100, 2).
    Hidden: 512 → 512 → 512 (ReLU + dropout).
    Z-scoring is baked into the forward pass via registered buffers so the
    same model can be used for training and optimization without any extra
    normalization plumbing at call sites.
    """

    def __init__(self,
                 n_det:       int = N_DETECTORS,
                 primary_dim: int = PRIMARY_DIM,
                 hidden:      int = 512,
                 dropout:     float = 0.1):
        super().__init__()
        self.n_det       = n_det
        self.primary_dim = primary_dim

        in_dim  = primary_dim + 2 * n_det
        out_dim = 2 * n_det

        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, hidden), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, hidden), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, hidden), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, hidden), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, hidden), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, hidden), nn.ReLU(),
            nn.Linear(hidden, out_dim),
        )

        self.register_buffer("in_mean",  torch.zeros(in_dim))
        self.register_buffer("in_std",   torch.ones(in_dim))
        self.register_buffer("out_mean", torch.zeros(out_dim))
        self.register_buffer("out_std",  torch.ones(out_dim))

    def set_normalization(self, stats: dict):
        """Copy z-score buffers from `compute_normalization()` output."""
        self.in_mean.copy_(stats["in_mean"])
        self.in_std.copy_(stats["in_std"])
        self.out_mean.copy_(stats["out_mean"])
        self.out_std.copy_(stats["out_std"])

    def forward(self, primary: torch.Tensor, xy: torch.Tensor) -> torch.Tensor:
        """
        Args:
            primary : (B, primary_dim)
            xy      : (B, n_det, 2)
        Returns:
            (B, n_det, 2) — column 0 = E, column 1 = T, in unnormalized units.
        """
        B = primary.shape[0]
        flat   = torch.cat([primary, xy.reshape(B, -1)], dim=1)    # (B, 205)
        flat_n = (flat - self.in_mean) / self.in_std
        out_n  = self.net(flat_n)                                   # (B, 200)
        out    = out_n * self.out_std + self.out_mean

        E_out = out[:, :self.n_det]
        T_out = out[:, self.n_det:]
        return torch.stack([E_out, T_out], dim=-1)                 # (B, n_det, 2)
